openapi: 3.1.1
info:
  title: DEG Energy Trade Ledger Attributes
  version: 0.3.0
  x-profile-id: profiles/deg/energy-trade-ledger/v0.3
  description: >
    Attribute schemas for energy trade ledger records.
    These types represent the domain model for the DEG contract ledger service,
    providing immutable, multi-party records of energy trade lifecycles.

    API specification with paths is at: ../api/deg_contract_ledger.yaml

components:
  schemas:
    ########################################################################
    # LEDGER RECORD — Core ledger entry
    ########################################################################
    LedgerRecord:
      type: object
      additionalProperties: false
      required:
        - recordId
        - transactionId
        - orderItemId
        - platformIdBuyer
        - platformIdSeller
        - discomIdBuyer
        - discomIdSeller
        - buyerId
        - sellerId
      x-jsonld:
        "@context": ./context.jsonld
        "@type": LedgerRecord
      description: >
        Canonical ledger record representing an energy trade.
        Immutable once created, with policy-controlled field-level updates.
      properties:
        recordId:
          type: string
          description: Unique ledger record identifier (generated by ledger service).
          example: "rec-9f8a2c"
          x-jsonld: { "@id": recordId }

        transactionId:
          type: string
          description: Beckn transaction identifier. Part of uniqueness key (transactionId + orderItemId).
          example: "tx-123"
          x-jsonld: { "@id": transactionId }

        orderItemId:
          type: string
          description: Order item identifier. Part of uniqueness key (transactionId + orderItemId).
          example: "item-1"
          x-jsonld: { "@id": orderItemId }

        creationTime:
          type: string
          format: date-time
          description: Timestamp when the record was created (generated by ledger).
          example: "2026-01-15T10:20:31Z"
          x-jsonld: { "@id": "schema:dateCreated" }

        platformIdBuyer:
          type: string
          description: Identifier of the buyer's trading platform (BAP).
          example: "bap.buyer-platform.example"
          x-jsonld: { "@id": platformIdBuyer }

        platformIdSeller:
          type: string
          description: Identifier of the seller's trading platform (BPP).
          example: "bpp.seller-platform.example"
          x-jsonld: { "@id": platformIdSeller }

        discomIdBuyer:
          type: string
          description: Identifier of the distribution company serving the buyer.
          example: "DISCOM_A"
          x-jsonld: { "@id": discomIdBuyer }

        discomIdSeller:
          type: string
          description: Identifier of the distribution company serving the seller.
          example: "DISCOM_B"
          x-jsonld: { "@id": discomIdSeller }

        buyerId:
          type: string
          description: Unique buyer identifier (e.g., CA number, utility-assigned ID).
          example: "CA-0000123"
          x-jsonld: { "@id": buyerId }

        sellerId:
          type: string
          description: Unique seller identifier (e.g., DER ID, prosumer ID).
          example: "DER-9981"
          x-jsonld: { "@id": sellerId }

        tradeTime:
          type: string
          format: date-time
          description: Timestamp when the trade agreement was finalized.
          example: "2026-01-15T10:20:30Z"
          x-jsonld: { "@id": tradeTime }

        deliveryStartTime:
          type: string
          format: date-time
          description: Timestamp when energy delivery begins.
          example: "2026-01-15T11:00:00Z"
          x-jsonld: { "@id": deliveryStartTime }

        deliveryEndTime:
          type: string
          format: date-time
          description: Timestamp when energy delivery ends.
          example: "2026-01-15T11:30:00Z"
          x-jsonld: { "@id": deliveryEndTime }

        tradeDetails:
          type: array
          description: Trade specifications (type, quantity, unit).
          items:
            $ref: "#/components/schemas/TradeDetail"
          x-jsonld: { "@id": tradeDetails }

        buyerFulfillmentValidationMetrics:
          type: array
          description: Validation metrics recorded by the buyer-side discom.
          items:
            $ref: "#/components/schemas/ValidationMetric"
          x-jsonld: { "@id": buyerFulfillmentValidationMetrics }

        sellerFulfillmentValidationMetrics:
          type: array
          description: Validation metrics recorded by the seller-side discom.
          items:
            $ref: "#/components/schemas/ValidationMetric"
          x-jsonld: { "@id": sellerFulfillmentValidationMetrics }

        statusBuyerDiscom:
          $ref: "#/components/schemas/TradeStatus"
          description: Trade status as recorded by the buyer-side discom.
          x-jsonld: { "@id": statusBuyerDiscom }

        statusSellerDiscom:
          $ref: "#/components/schemas/TradeStatus"
          description: Trade status as recorded by the seller-side discom.
          x-jsonld: { "@id": statusSellerDiscom }

        rowDigest:
          type: string
          description: Cryptographic digest of the canonical row state for integrity verification.
          example: "sha256:6d7a...f09c"
          x-jsonld: { "@id": rowDigest }

    ########################################################################
    # TRADE DETAIL — Trade specification
    ########################################################################
    TradeDetail:
      type: object
      additionalProperties: false
      required: [tradeType, tradeQty, tradeUnit]
      x-jsonld:
        "@context": ./context.jsonld
        "@type": TradeDetail
      description: Specification of energy quantity, type, and unit for a trade.
      properties:
        tradeType:
          $ref: "#/components/schemas/TradeType"
          x-jsonld: { "@id": tradeType }

        tradeQty:
          type: number
          minimum: 0
          description: Numeric quantity of energy or capacity traded.
          example: 12.5
          x-jsonld: { "@id": tradeQty }

        tradeUnit:
          $ref: "#/components/schemas/TradeUnit"
          x-jsonld: { "@id": tradeUnit }

    ########################################################################
    # VALIDATION METRIC — Fulfillment validation
    ########################################################################
    ValidationMetric:
      type: object
      additionalProperties: false
      required: [validationMetricType, validationMetricValue]
      x-jsonld:
        "@context": ./context.jsonld
        "@type": ValidationMetric
      description: Fulfillment validation measurement recorded by a discom.
      properties:
        validationMetricType:
          $ref: "#/components/schemas/MetricType"
          x-jsonld: { "@id": validationMetricType }

        validationMetricValue:
          type: number
          description: Numeric value of the validation measurement.
          example: 11.9
          x-jsonld: { "@id": validationMetricValue }

    ########################################################################
    # ENUMERATIONS
    ########################################################################
    LedgerRole:
      type: string
      enum: [BUYER, SELLER, BUYER_DISCOM, SELLER_DISCOM]
      description: >
        Role of the participant in ledger operations.
        - BUYER/SELLER: Platform roles, use /ledger/put
        - BUYER_DISCOM/SELLER_DISCOM: Distribution company roles, use /ledger/record
      x-jsonld:
        "@context": ./context.jsonld
        "@type": LedgerRole

    TradeType:
      type: string
      enum: [ENERGY, RAISE_CAPACITY, LOWER_CAPACITY, PFR, SFR, TC, BDR]
      description: >
        Classification of the energy trade product.
        - ENERGY: Pure energy trade (kWh)
        - RAISE_CAPACITY/LOWER_CAPACITY: Frequency regulation
        - PFR: Primary Frequency Response
        - SFR: Secondary Frequency Response
        - TC: Tertiary Control / reserve
        - BDR: Behavioral Demand Response
      x-jsonld:
        "@context": ./context.jsonld
        "@type": TradeType

    TradeUnit:
      type: string
      enum: [KWH, KW]
      description: >
        Unit of measurement for trade quantities.
        - KWH: Kilowatt-hours (energy)
        - KW: Kilowatts (power/capacity)
      x-jsonld:
        "@context": ./context.jsonld
        "@type": TradeUnit

    MetricType:
      type: string
      enum:
        - ACTUAL_PUSHED
        - ACTUAL_PULLED
        - SETPOINT_FOLLOWING_ERROR
        - ACTUAL_RAISE_CAPACITY
        - ACTUAL_LOWER_CAPACITY
        - FREQUENCY_RESPONSE_ERROR
        - ACTUAL_DEMAND_REDUCTION
        - AVAILABILITY
      description: >
        Type of fulfillment validation metric.
        - ACTUAL_PUSHED: Energy injected to grid (seller)
        - ACTUAL_PULLED: Energy consumed from grid (buyer)
        - SETPOINT_FOLLOWING_ERROR: Deviation from agreed setpoint
        - ACTUAL_RAISE/LOWER_CAPACITY: Frequency regulation delivery
        - FREQUENCY_RESPONSE_ERROR: Frequency response performance error
        - ACTUAL_DEMAND_REDUCTION: BDR program achievement
        - AVAILABILITY: Resource availability percentage
      x-jsonld:
        "@context": ./context.jsonld
        "@type": MetricType

    TradeStatus:
      type: string
      enum:
        - PENDING
        - CONFIRMED
        - CANCELLED_OUTAGE
        - CANCELLED_POL_VIOLATION
        - CURTAILED_OUTAGE
        - CURTAILED_POL_VIOLATION
        - COMPLETED
      description: >
        Trade lifecycle status.
        - PENDING: Awaiting confirmation or delivery
        - CONFIRMED: Scheduled for delivery
        - CANCELLED_*: Full cancellation (outage or policy)
        - CURTAILED_*: Partial delivery (outage or policy)
        - COMPLETED: Successfully completed
      x-jsonld:
        "@context": ./context.jsonld
        "@type": TradeStatus
